### ISSUE TITLE
Cannot find module index.js while starting from hosting service

### ISSUE THREAD

**Issue by LeonGuerreroGit** [sammwyy/open-taiko#2]
Error: Cannot find module '/opt/render/project/src/dist/index.js'. Please verify that the package.json has a valid "main" entry
   at tryPackage (internal/modules/cjs/loader.js:308:19)
   at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)
   at resolveMainPath (internal/modules/run_main.js:12:25)
   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)
   at internal/main/run_main_module.js:17:47 {
        code: 'MODULE_NOT_FOUND',
        path: '/opt/render/project/src/package.json',
        requestPath: '/opt/render/project/src'
        }

**Comment by keisanng** [comment]
Did you run the build command?
